import type { Command } from 'commander';
import { registerInitCommand } from './init.js';
import { registerLoginCommand } from './login.js';
import { registerClaimCommand } from './claim.js';
import { registerStatusCommand } from './status.js';
import { registerFilesCommand, registerLsCommand } from './files.js';
import { registerReadCommand, registerCatCommand } from './read.js';
import { registerAppendCommand } from './append.js';
import { registerWriteCommand } from './write.js';
import { registerRmCommand } from './rm.js';
import { registerMkdirCommand } from './mkdir.js';
import { registerSearchCommand } from './search.js';
import { registerExportCommand } from './export.js';
import { registerExportStatusCommand } from './export-status.js';
import { registerExportDownloadCommand } from './export-download.js';
import { registerCheckKeysCommand } from './check-keys.js';
import { registerRecoverCommand } from './recover.js';
import { registerMvCommand } from './mv.js';
import { registerRotateCommand } from './rotate.js';
import { registerSettingsCommand } from './settings.js';
import { registerAgentsCommand } from './agents.js';
import { registerDeletedCommand } from './deleted.js';

export function registerAllCommands(program: Command): void {
  registerInitCommand(program);
  registerLoginCommand(program);
  registerClaimCommand(program);
  registerStatusCommand(program);
  registerFilesCommand(program);
  registerLsCommand(program);
  registerReadCommand(program);
  registerCatCommand(program);
  registerAppendCommand(program);
  registerWriteCommand(program);
  registerRmCommand(program);
  registerMkdirCommand(program);
  registerSearchCommand(program);
  registerExportCommand(program);
  registerExportStatusCommand(program);
  registerExportDownloadCommand(program);
  registerCheckKeysCommand(program);
  registerRecoverCommand(program);
  registerMvCommand(program);
  registerRotateCommand(program);
  registerSettingsCommand(program);
  registerAgentsCommand(program);
  registerDeletedCommand(program);
}

export { registerInitCommand } from './init.js';
export { registerLoginCommand } from './login.js';
export { registerClaimCommand } from './claim.js';
export { registerStatusCommand } from './status.js';
export { registerFilesCommand, registerLsCommand } from './files.js';
export { registerReadCommand, registerCatCommand } from './read.js';
export { registerAppendCommand } from './append.js';
export { registerWriteCommand } from './write.js';
export { registerRmCommand } from './rm.js';
export { registerMkdirCommand } from './mkdir.js';
export { registerCheckKeysCommand } from './check-keys.js';
export { registerRecoverCommand } from './recover.js';
export { registerMvCommand } from './mv.js';
export { registerRotateCommand } from './rotate.js';
export { registerSettingsCommand } from './settings.js';
export { registerSearchCommand } from './search.js';
export { registerExportCommand } from './export.js';
export { registerExportStatusCommand } from './export-status.js';
export { registerExportDownloadCommand } from './export-download.js';
export { registerAgentsCommand } from './agents.js';
export { registerDeletedCommand } from './deleted.js';
