import { defineConfig } from '@hey-api/openapi-ts';

export default defineConfig({
  // Use bundled spec (generated by redocly bundle) for hey-api
  // The multi-file spec doesn't work well with hey-api
  input: './openapi.bundled.yaml',
  output: {
    path: './src/generated/client',
  },
  plugins: [
    '@hey-api/typescript',
    {
      name: 'zod',
      output: '../schemas',
    },
  ],
});

