/**
 * Minimal type stubs for binary response types generated by OpenAPI codegen.
 *
 * The @hey-api/openapi-ts generator produces `Blob | File` types for
 * `format: binary` responses. These types require DOM lib, but this package
 * is also consumed by server code (Bun/Node.js) that doesn't have DOM.
 *
 * This file provides minimal type definitions to satisfy TypeScript without
 * pulling in the full DOM lib (which would pollute the namespace with
 * window, document, localStorage, etc. that don't exist in server contexts).
 *
 * @see packages/shared/src/generated/client/types.gen.ts (ExportWorkspaceResponse)
 */

declare global {
  interface Blob {
    readonly size: number;
    readonly type: string;
    slice(start?: number, end?: number, contentType?: string): Blob;
    text(): Promise<string>;
    arrayBuffer(): Promise<ArrayBuffer>;
  }

  interface File extends Blob {
    readonly name: string;
    readonly lastModified: number;
  }
}

export {};

